;
; Script generated by the ASCOM Driver Installer Script Generator 7.0.0.0
; Generated by Juanjo López on 29/09/2025 (UTC)
;
[Setup]
AppID={{a712827f-ae52-4a47-bedd-fb3735efc64f}
AppName=ASCOM autoFilterWheel FilterWheel Driver
AppVerName=ASCOM autoFilterWheel FilterWheel Driver v2.0.0
AppVersion=v2.0.0
AppPublisher=Juanjo López
AppPublisherURL=https://github.com/juanjol
AppSupportURL=https://ascomtalk.groups.io/g/Help
AppUpdatesURL=https://ascom-standards.org/
VersionInfoVersion=2.0.0
MinVersion=6.1.7601
DefaultDirName="{cf}\ASCOM\FilterWheel"
DisableDirPage=yes
DisableProgramGroupPage=yes
OutputDir="./dist/"
OutputBaseFilename="autoFilterWheelSetup-v2.0.0"
Compression=lzma
SolidCompression=yes
; Relative paths for GitHub Actions compatibility
; WizardImageFile will use default if not found
; LicenseFile will use default if not found
; {cf}\ASCOM\Uninstall\FilterWheel folder created by Platform, always
UninstallFilesDir="{cf}\ASCOM\Uninstall\FilterWheel\autoFilterWheel"

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Dirs]
Name: "{cf}\ASCOM\Uninstall\FilterWheel\autoFilterWheel"
; TODO: Add subfolders below {app} as needed (e.g. Name: "{app}\MyFolder")

[Files]
Source: "bin\Release\ASCOM.autoFilterWheel.exe"; DestDir: "{app}"; Flags: ignoreversion replacesameversion restartreplace uninsrestartdelete; AfterInstall: RegASCOM()
Source: "bin\Release\ASCOM.autoFilterWheel.exe.config"; DestDir: "{app}"; Flags: ignoreversion replacesameversion
Source: "bin\Release\ASCOM.*.dll"; DestDir: "{app}"; Flags: ignoreversion replacesameversion
Source: "bin\Release\ASCOM.*.xml"; DestDir: "{app}"; Flags: skipifsourcedoesntexist ignoreversion
; Require a read-me HTML to appear after installation, maybe driver's Help doc
Source: "ReadMe.htm"; DestDir: "{app}"; Flags: isreadme ignoreversion

;Only if COM Local Server
[Run]
; Wait for registration to complete before continuing
Filename: "{app}\ASCOM.autoFilterWheel.exe"; Parameters: "/regserver"; Flags: runhidden waituntilterminated


;Only if COM Local Server
[UninstallRun]
; Unregister before uninstalling files
Filename: "{app}\ASCOM.autoFilterWheel.exe"; Parameters: "/unregserver"; Flags: runhidden waituntilterminated



;  DCOM setup for COM local Server, needed for TheSky
[Registry]
; TODO: If needed set this value to the FilterWheel CLSID of your driver (mind the leading/extra '{')
#define AppClsid "{{e9752f76-629c-4e84-a248-3262f3da0e1d}"

; set the DCOM access control for TheSky on the FilterWheel interface
Root: HKCR; Subkey: CLSID\{#AppClsid}; ValueType: string; ValueName: AppID; ValueData: {#AppClsid}
Root: HKCR; Subkey: AppId\{#AppClsid}; ValueType: string; ValueData: "ASCOM autoFilterWheel FilterWheel Driver"
Root: HKCR; Subkey: AppId\{#AppClsid}; ValueType: string; ValueName: AppID; ValueData: {#AppClsid}
Root: HKCR; Subkey: AppId\{#AppClsid}; ValueType: dword; ValueName: AuthenticationLevel; ValueData: 1
; set the DCOM key for the executable as a whole
Root: HKCR; Subkey: AppId\ASCOM.autoFilterWheel.exe; ValueType: string; ValueName: AppID; ValueData: {#AppClsid}
; CAUTION! DO NOT EDIT - DELETING ENTIRE APPID TREE WILL BREAK WINDOWS!
Root: HKCR; Subkey: AppId\{#AppClsid}; Flags: uninsdeletekey
Root: HKCR; Subkey: AppId\ASCOM.autoFilterWheel.exe; Flags: uninsdeletekey

[Code]
const
   REQUIRED_PLATFORM_VERSION = 6.2;    // Set this to the minimum required ASCOM Platform version for this application

//
// Function to return the ASCOM Platform's version number as a double.
//
function PlatformVersion(): Double;
var
   PlatVerString : String;
begin
   Result := 0.0;  // Initialise the return value in case we can't read the registry
   try
      if RegQueryStringValue(HKEY_LOCAL_MACHINE_32, 'Software\ASCOM','PlatformVersion', PlatVerString) then 
      begin // Successfully read the value from the registry
         Result := StrToFloat(PlatVerString); // Create a double from the X.Y Platform version string
      end;
   except                                                                   
      ShowExceptionMessage;
      Result:= -1.0; // Indicate in the return value that an exception was generated
   end;
end;

//
// Before the installer UI appears, verify that the required ASCOM Platform version is installed.
//
function InitializeSetup(): Boolean;
var
   PlatformVersionNumber : double;
 begin
   Result := FALSE;  // Assume failure
   PlatformVersionNumber := PlatformVersion(); // Get the installed Platform version as a double
   If PlatformVersionNumber >= REQUIRED_PLATFORM_VERSION then	// Check whether we have the minimum required Platform or newer
      Result := TRUE
   else
      if PlatformVersionNumber = 0.0 then
         MsgBox('No ASCOM Platform is installed. Please install Platform ' + Format('%3.1f', [REQUIRED_PLATFORM_VERSION]) + ' or later from https://www.ascom-standards.org', mbCriticalError, MB_OK)
      else 
         MsgBox('ASCOM Platform ' + Format('%3.1f', [REQUIRED_PLATFORM_VERSION]) + ' or later is required, but Platform '+ Format('%3.1f', [PlatformVersionNumber]) + ' is installed. Please install the latest Platform before continuing; you will find it at https://www.ascom-standards.org', mbCriticalError, MB_OK);
end;

// Function to kill any running instances of the driver
function KillRunningInstances(): Boolean;
var
  ResultCode: Integer;
begin
  Result := True;
  // Try to kill any running instances using taskkill
  Exec('taskkill', '/F /IM ASCOM.autoFilterWheel.exe', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  Sleep(1000);
end;

// Function to clean up old driver completely
procedure CleanupOldDriver();
var
  ResultCode: Integer;
  AppPath: String;
  P: Variant;
  I: Integer;
begin
  AppPath := ExpandConstant('{cf}\ASCOM\FilterWheel\ASCOM.autoFilterWheel.exe');

  // Step 1: Unregister from ASCOM Profile
  try
    P := CreateOleObject('ASCOM.Utilities.Profile');
    P.DeviceType := 'FilterWheel';
    P.Unregister('ASCOM.autoFilterWheel.FilterWheel');
    Sleep(500);
  except
    // Ignore errors if not registered
  end;

  // Step 2: Unregister COM server if file exists
  if FileExists(AppPath) then
  begin
    Exec(AppPath, '/unregserver', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
    Sleep(1000);
  end;

  // Step 3: Kill any running instances
  KillRunningInstances();

  // Step 4: Delete all driver files
  if FileExists(AppPath) then
  begin
    // Try multiple times in case file is locked
    for I := 1 to 3 do
    begin
      if DeleteFile(AppPath) then
        Break
      else
        Sleep(500);
    end;
  end;

  // Step 5: Clean up registry COM entries
  RegDeleteKeyIncludingSubkeys(HKCR, 'CLSID\{e9752f76-629c-4e84-a248-3262f3da0e1d}');
  RegDeleteKeyIncludingSubkeys(HKCR, 'ASCOM.autoFilterWheel.FilterWheel');

  Sleep(500);
end;

// Code to enable the installer to uninstall previous versions of itself when a new version is installed
procedure CurStepChanged(CurStep: TSetupStep);
var
  ResultCode: Integer;
  UninstallExe: String;
  UninstallRegistry: String;
begin
  if (CurStep = ssInstall) then // Install step has started
  begin
    // Step 1: Always clean up old driver first (even if no uninstaller found)
    CleanupOldDriver();

    // Step 2: Run official uninstaller if it exists
    UninstallRegistry := ExpandConstant('Software\Microsoft\Windows\CurrentVersion\Uninstall\{#SetupSetting("AppId")}' + '_is1');
    if RegQueryStringValue(HKLM, UninstallRegistry, 'UninstallString', UninstallExe) then
    begin
      MsgBox('Removing previous version...', mbInformation, MB_OK);
      Exec(RemoveQuotes(UninstallExe), '/VERYSILENT /SUPPRESSMSGBOXES /NORESTART /FORCECLOSEAPPLICATIONS', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
      Sleep(2000);
    end;

    // Step 3: Final cleanup to ensure everything is clean
    CleanupOldDriver();
    Sleep(1000);
  end;
end;

//
// Register the driver with ASCOM after installation
//
procedure RegASCOM();
var
   P: Variant;
   Retry: Integer;
begin
   // Try multiple times in case of timing issues
   for Retry := 1 to 3 do
   begin
     try
       Sleep(500); // Wait a bit before registering
       P := CreateOleObject('ASCOM.Utilities.Profile');
       P.DeviceType := 'FilterWheel';
       P.Register('ASCOM.autoFilterWheel.FilterWheel', 'autoFilterWheel ASCOM driver');
       Exit; // Success, exit
     except
       if Retry = 3 then
         MsgBox('Warning: Could not register driver with ASCOM Chooser. You may need to reinstall.', mbError, MB_OK);
       Sleep(1000); // Wait before retry
     end;
   end;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
   P: Variant;
   AppPath: String;
   ResultCode: Integer;
begin
   if CurUninstallStep = usUninstall then
   begin
     // Step 1: Unregister from ASCOM Profile
     try
       P := CreateOleObject('ASCOM.Utilities.Profile');
       P.DeviceType := 'FilterWheel';
       P.Unregister('ASCOM.autoFilterWheel.FilterWheel');
       Sleep(500);
     except
       // Ignore errors during uninstall
     end;

     // Step 2: Kill any running instances
     KillRunningInstances();

     // Step 3: Clean up registry COM entries
     RegDeleteKeyIncludingSubkeys(HKCR, 'CLSID\{e9752f76-629c-4e84-a248-3262f3da0e1d}');
     RegDeleteKeyIncludingSubkeys(HKCR, 'ASCOM.autoFilterWheel.FilterWheel');
  end;
end;
